import type { Metadata } from "next";
import "../globals.css"
import React from "react";
import {adminFontTitle} from "@/assets/fonts";


export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({children}: Readonly<{children: React.ReactNode}>) {
    return (
        <html lang="fr">
            <body className={`${adminFontTitle.className}`}>
            {children}
            </body>
        </html>
    );
}
